# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded avltree 1.0 [list source [file join $dir avltree.tcl]]
package ifneeded heap 1.0 [list source [file join $dir heap.tcl]]
package ifneeded mrfclip 1.0 [list source [file join $dir mrfclip.tcl]]
package ifneeded mrfclip::chain 1.0 [list source [file join $dir mrfclip.chain.tcl]]
package ifneeded mrfclip::event 1.0 [list source [file join $dir mrfclip.event.tcl]]
package ifneeded mrfclip::point 1.0 [list source [file join $dir mrfclip.point.tcl]]
